In [1]:
# Initialize Otter
import otter
grader = otter.Notebook("practice.ipynb")

In [2]:
import test

# Lab-P3: Learning an API and some functions

**WARNING:** Please go through Segments 1 and 2 of [lab-p3](https://git.doit.wisc.edu/cdis/cs/courses/cs220/cs220-f22-projects/-/tree/main/lab-p3) **before** you start to solve this notebook.

## Task 3.1: Calling functions in the `project` module

You have already learned how to learn the *API* of the `project.py` module. You will now demonstrate your ability to call the functions in this module.

In [6]:
# Include the relevant import statements in this cell

import project # we have imported the project module for you here; you will have to add the import statement in p3

In [8]:
project.init("lab.csv") # we have also loaded in 'lab.csv' for you here; you will have to load the data yourself in p3
project.dump()
# You may call the dump() function here to test if you have loaded the dataset correctly.

WARNING!  Opening a path other than car_sales_data.csv.  That's fine for testing your code yourself, but car_sales_data.csv will be the only file around when we test your code for grading.
Chevy Bolt [ID: 21]
  2017: 23297 cars sold
  2018: 18019 cars sold
  2019: 16313 cars sold

Chrysler Pacifica Plug-in Hybrid [ID: 3664]
  2017: 2981 cars sold
  2018: 7062 cars sold
  2019: 5811 cars sold

Honda Clarity Plug-in [ID: 426]
  2017: 903 cars sold
  2018: 18602 cars sold
  2019: 10728 cars sold

Porsche Cayenne S E-Hybrid [ID: 6273]
  2017: 1574 cars sold
  2018: 1022 cars sold
  2019: 1140 cars sold

Tesla Model 3 [ID: 850]
  2017: 1770 cars sold
  2018: 139782 cars sold
  2019: 154840 cars sold



**Question 1:** What is the `id` of the *Tesla Model 3*?

In [9]:
# we have done this one for you
model_3_id = project.get_id("Tesla Model 3")
model_3_id

850

In [10]:
grader.check("q1")

q1 results: All test cases passed!

**Question 2:** What is the `id` of the *Honda Clarity Plug-in*?

In [11]:
# you will have to do this yourself; replace the ... with your answer
# NOTE: assigning `clarity_id = 426` => is considered hardcoding
# if you do this in p3, you will lose points during manual code review
clarity_id = project.get_id('Honda Clarity Plug-in')
clarity_id

426

In [12]:
grader.check("q2")

q2 results: All test cases passed!

**Question 3:** What is the `id` of the *Chrysler Pacifica Plug-in Hybrid*?

In [13]:
# compute and store the answer in the variable 'pacifica_id'
pacifica_id = project.get_id('Chrysler Pacifica Plug-in Hybrid')
# display the variable 'pacifica_id' here
pacifica_id

3664

In [14]:
grader.check("q3")

q3 results: All test cases passed!

### Task 3.1.1: Avoiding index hardcoding

You should now have a good sense of how the `project.get_id()` function works. You will now move on to the `project.get_sales()` function. Read the documentation of this function, if you haven't already. Let us now call this function and see how it operates:

**Question 4:** How many *Tesla Model 3* cars were sold in *2019*?

In [15]:
# run this cell for now
model_3_sales_2019 = project.get_sales(850, 2019) # 850 is the `car_id` of Tesla Model 3
model_3_sales_2019

154840

In [16]:
grader.check("q4")

q4 results: All test cases passed!

## NOTE: Even though you passed the test, this is considered hardcoding!

You were asked how many *Tesla Model 3* cars were sold in *2019*. The `id` *850* was not provided to you as part of the question. You have no reason to expect that the dataset might not change in the future and that the ids will not be updated. Furthermore, by hardcoding the `id` into your answer, you are limiting its ability to be used for other datasets, where *Tesla Model 3* might have a different `id`.

**Warning:** Since you used some information that was **not** explicitly provided to you as part of the question, this is considered **hardcoding**, and even if you pass the autograder, you will lose points for this, during manual code review.

Let us now see the **correct** way to answer the previous question.

**Question 5:** How many *Tesla Model 3* cars were sold in *2019*?

In [17]:
# this is the *correct* way to solve this question without hardcoding any indices
model_3_id = project.get_id('Tesla Model 3')
model_3_sales_2019 = project.get_sales(model_3_id, 2019)
model_3_sales_2019

154840

In [18]:
grader.check("q5")

q5 results: All test cases passed!

**Question 6:** How many *Porsche Cayenne S E-Hybrid* cars were sold in *2017*?

You **must not** hardcode the `id` of the car

In [21]:
# replace the ... with the correct code

cayenne_id = project.get_id("Porsche Cayenne S E-Hybrid")
cayenne_sales_2017 = project.get_sales(cayenne_id, 2017)
cayenne_sales_2017

1574

In [22]:
grader.check("q6")

q6 results: All test cases passed!

**Question 7:** How many *Chevy Bolt* cars were sold in *2018*?

You **must not** hardcode the `id` of the car

In [24]:
# compute and store the answer in the variable 'bolt_sales_2018'
chevy_bolt_id = project.get_id("Chevy Bolt")
bolt_sales_2018 = project.get_sales(chevy_bolt_id, 2018)
# display the variable 'bolt_sales_2018' here
bolt_sales_2018

18019

In [25]:
grader.check("q7")

q7 results: All test cases passed!

## Task 3.2: Calling and defining functions

You will first demonstrate how to call some *built-in* functions (`max` and `min`) that will be useful for you in p3.

**Question 8:** What is the *minimum* of the three numbers: *220*, *319*, and *320*?

In [26]:
# we have done this one for you
min_three_numbers = min(220, 319, 320)
min_three_numbers

220

In [27]:
grader.check("q8")

q8 results: All test cases passed!

**Question 9:** What is the *minimum* of the two numbers: *220* and *200*?

In [29]:
# compute and store the answer in the variable 'min_two_numbers'.
min_two_numbers = min(220,200)
# display the variable 'min_two_numbers' here

In [30]:
grader.check("q9")

q9 results: All test cases passed!

**Question 10:** What is the *maximum* of the three numbers: *200*, *300*, and *400*?

**Hint:** Just like the `min()` function, there is a `max()` function. You can either inspect or read its documentation to figure out how to use it.

In [ ]:
# compute and store the answer in the variable 'max_three_numbers'.

# display the variable 'max_three_numbers' here

In [ ]:
grader.check("q10")

### Task 3.2.1: Defining your own functions

You will now demonstrate how to define your own functions and how to call them.

### Function 1: `get_avg_drop_lowest(score1, score2, score3)`

- This function will have three parameters, `score1`, `score2`, and `score3`.
- It should add up the 3 scores, subtract out the smallest of these scores, and then determine the average of the remaining two.

For example, given the three scores `2, 4, 7`, your function should sum all the scores together `2 + 4 + 7` and then subtract `2`. Finally, it should return the average of the two remaining scores `(4 + 7)/2 = 5.5`.

You will be provided with some code snippets to start with, but you will have to fill out the rest of the function. If you are not sure how to write this function, ask your TA/PM for help.

In [ ]:
def get_avg_drop_lowest(score1, score2, score3):
    # replace all the ... with your own code
    smallest = ...
    sum_of_larger_two = ...
    avg = ...
    return avg

**Question 11:** What is the output of `get_avg_drop_lowest(18, 20, 17)`?

In [ ]:
# we have done this one for you
avg_drop_lowest_18_20_17 = get_avg_drop_lowest(18, 20, 17)
avg_drop_lowest_18_20_17

In [ ]:
grader.check("q11")

**Question 12:** What is the output of `get_avg_drop_lowest(40, 45, 35)`?

In [ ]:
# compute and store the answer in the variable 'avg_drop_lowest_40_45_35'

# display the variable 'avg_drop_lowest_40_45_35' here

In [ ]:
grader.check("q12")

### Function 2: `get_range(num1, num2, num3, num4)`

- This function will have four parameters, `num1`, `num2`, `num3`, and `num4`.
- It should find the maximum of the four numbers, and the minimum of the four numbers, and subtract the minimum from the maximum.

For example, given the four numbers `1, 2, 3, 4`, your function should subtract the minimum `1` from the maximum `4`, and return `4 - 1 = 3`.

You will be provided with some code snippets to start with, but you will have to fill out the rest of the function. If you are not sure how to write this function, ask your TA/PM for help.

In [ ]:
def get_range(num1, num2, num3, num4):
    # replace all the ... with your own code
    maximum = ...
    # define a variable called `minimum` and store the minimum of the four numbers as its value
    
    range_four_nums = ...
    return range_four_nums

**Question 13:** What is the output of `get_range(10, 20, 40, 60)`?

In [ ]:
# compute and store the answer in the variable 'range_10_20_40_60'

# display the variable 'range_10_20_40_60' here

In [ ]:
grader.check("q13")

**Question 14:** What is the output of `get_range(40, 20, 10, 30)`?

In [ ]:
# compute and store the answer in the variable 'range_40_20_10_30'

# display the variable 'range_40_20_10_30' here

In [ ]:
grader.check("q14")

### Function 3: `change_in_value_per_year(year1, value1, year2, value2)`

- This function will have four parameters, `year1`, `value1`, `year2`, and `value2`.
- `year1` and `year2` will be two different years represented as `int` and `value1` and `value2` will be the *value* of `year1` and `year2` respectively.
- This function should find the average yearly change in *value* between `year1` and `year2`.

**Hint:** This function basically computes the slope of the line that passes through the points (`year1`, `value1`) and (`year2`, `value2`).

For example, if we are given the inputs `year1 = 2017`, `value1 = 5`, `year2 = 2022`, and `value2 = 0`, then the output of the function should be `(0 - 5)/(2022 - 2017) = -1.0`.

You will be provided with some code snippets to start with, but you will have to fill out the rest of the function. Note that you will have to define a very similar function in p3, so this will be good practice for you. If you are not sure how to write this function, ask your TA/PM for help.

In [39]:
def change_in_value_per_year(year1, value1, year2=2022, value2=6): # DO NOT EDIT THIS LINE
    pass # this statement tells Python to do nothing.
    # since this function has no code inside, we have added the pass statement inside so the code does not crash.
    # once you have added code to this function, you can (and should) remove the pass statement as it does nothing.

    # TODO: find the change in *value* between `year1` and `year2` and store it in a variable `change_in_value`
    # TODO: find the number of years between `year1` and `year2` and store it in a variable `num_years`
    # TODO: compute the average change in value between `year1` and `year2` and store it in a variable `change_per_year`
    # TODO: you *should* use the variables `change_in_value` and `num_years` to define this variable `change_per_year`
    # TODO: return the variable `change_per_year`   

**Question 15:** What is the output of `change_in_value_per_year(2019, 12, 2020, 4)`?

In [46]:
# compute and store the answer in the variable 'change_per_year_2019_12_2020_4'
change_per_year_2019_12_2020_4 = change_in_value_per_year(2019, 12, 2020, 4)
# display the variable 'change_per_year_2019_12_2020_4' here
change_per_year_2019_12_2020_4

In [40]:
grader.check("q15")

q15 results:
    q15 - 1 result:
        Trying:
            test.check("q15", change_per_year_2019_12_2020_4)
        Expecting:
            True
        **********************************************************************
        Line 1, in q15 0
        Failed example:
            test.check("q15", change_per_year_2019_12_2020_4)
        Expected:
            True
        Got:
            <b style='color: red;'>ERROR:</b> expected to find type float but found type NoneType

**Question 16:** What is the output of `change_in_value_per_year(2015, 8, 2018, 11)`?

In [ ]:
# compute and store the answer in the variable 'change_per_year_2015_8_2018_11'

# display the variable 'change_per_year_2015_8_2018_11' here

In [ ]:
grader.check("q16")

### Task 3.2.2: Using default arguments

You will now demonstrate how to use default arguments in functions.

If you look back at the definition of `change_in_value_per_year()`, you notice that the parameters `year2` and `value2` were given the default arguments `2022` and `6` respectively. We will now use these default arguments in our function calls.

**Question 17:** Find the change in value per year when `year1` is *2020*, `value1` is *4*, `year2` is *2013*, and `value2` is *6*

In [44]:
# we have done this one for you
change_per_year_2020_4_2013_6 = change_in_value_per_year(2020, 4, 2013) # note that the default argument for `value2` is used
change_per_year_2020_4_2013_6

In [45]:
grader.check("q17")

q17 results:
    q17 - 1 result:
        Trying:
            test.check("q17", change_per_year_2020_4_2013_6)
        Expecting:
            True
        **********************************************************************
        Line 1, in q17 0
        Failed example:
            test.check("q17", change_per_year_2020_4_2013_6)
        Expected:
            True
        Got:
            <b style='color: red;'>ERROR:</b> expected to find type float but found type NoneType

**Question 18:**  Find the change in value per year when `year1` is *2018*, `value1` is *11*, `year2` is *2022*, and `value2` is *6*

You **must** use the default arguments (your call to `change_in_value_per_year` should **not** pass any more arguments than is absolutely necessary). Ask a TA/PM to review your code if you are unsure of your answer.

In [ ]:
# compute and store the answer in the variable 'change_per_year_2018_11_2022_6'

# display the variable 'change_per_year_2018_11_2022_6' here

In [ ]:
grader.check("q18")

**Question 19:** Find the change in value per year when `year1` is *2013*, `value1` is *3*, `year2` is *2022*, and `value2` is *2*

In [ ]:
# we have done this one for you
change_per_year_2013_3_2022_2 = change_in_value_per_year(2013, 3, value2=2) # note the use of positional arguments here
change_per_year_2013_3_2022_2

In [ ]:
grader.check("q19")

**Question 20:** Find the change in value per year when `year1` is *2016*, `value1` is *4*, `year2` is *2022*, and `value2` is *0*

In [ ]:
# compute and store the answer in the variable 'change_per_year_2016_4_2022_0'

# display the variable 'change_per_year_2016_4_2022_0' here

In [ ]:
grader.check("q20")

## That's it! You are done with lab-p3 and may start p3. You do not have to submit this practice notebook to Gradescope. Good luck!